const data = {
    units: [
        {
            id: 1,
            name: "Unit 5: Working 9 to 5",
            categories: {
                "Quick Check": [
                    { term: "It is necessary that I wear a helmet and protective clothing when I am at work.", definition: "race car driver" },
                    { term: "It is essential that my patients are comfortable and still while I work.", definition: "surgeon" },
                    { term: "It is important that I stay alert and watch my screen and instruments at all times to help pilots.", definition: "air traffic controller" },
                    { term: "I ask that visitors stay away from young animals to protect them from diseases.", definition: "zoologist" },
                    { term: "I specialize in constructions that utilize alternative sources of energy.", definition: "engineer" },
                    { term: "satisfaction", definition: "feeling of contentment" },
                    { term: "status", definition: "state or condition" },
                    { term: "entail", definition: "to involve or require" },
                    { term: "appreciate", definition: "to be grateful for" },
                    { term: "income", definition: "money received or earned" },
                    { term: "cooperate", definition: "to work together well" },
                    { term: "respectful", definition: "polite, showing consideration" },
                ],
                "Vocabulary Building": [
                    { term: "satisfaction", definition: "feeling of contentment" },
                    { term: "status", definition: "state or condition" },
                    { term: "entail", definition: "to involve or require" },
                    { term: "appreciate", definition: "to be grateful for" },
                    { term: "income", definition: "money received or earned" },
                    { term: "cooperate", definition: "to work together well" },
                    { term: "respectful", definition: "polite, showing consideration" },
                    { term: "analyze", definition: "to study closely" },
                    { term: "determine", definition: "to decide or discover" },
                    { term: "identifying", definition: "determining what something is" },
                ],
                "Real Talk": [
                    { term: "in a bind", definition: "in a difficult situation" },
                    { term: "help me out", definition: "do me a favor" },
                    { term: "cover", definition: "take someone's place, often in a work situation" },
                    { term: "keep it to yourself", definition: "not tell anyone" },
                    { term: "No kidding?", definition: "Really?" },
                    { term: "jump ship", definition: "leave a job suddenly, usually to go to a new job" },
                    { term: "take off", definition: "leave" },
                    { term: "Will do.", definition: "short for: I will do it." },
                ],
            },
        },
        {
            id: 2,
            name: "Unit 6: Going Green",
            categories: {
                "Vocabulary Building": [
                    { term: "allergens", definition: "substances that cause sensitivity or reactions in some people" },
                    { term: "identical", definition: "exactly the same" },
                    { term: "flair", definition: "a natural talent or ability" },
                    { term: "captive", definition: "confined, kept under restraint or control" },
                    { term: "infection", definition: "disease or sickness received from someone or something" },
                ],
                "Real Talk": [
                    { term: "relying", definition: "depending on" },
                    { term: "utility", definition: "basic service supplied by a business or facility such as electricity or running water" },
                    { term: "bold", definition: "strong and courageous" },
                    { term: "committed", definition: "dedicated" },
                    { term: "perspective", definition: "a way of seeing something" },
                    { term: "harsh", definition: "severe, difficult" },
                    { term: "enormous", definition: "extremely large" },
                    { term: "sacrifice", definition: "loss of something for a specific purpose" },
                ],
                "Fill in the Blank": [
                    { definition: "It's freezing in here. Why is the ___ set so high?", term: "air conditioner" },
                    { definition: "Half of the average family's energy ___ is used for heating and cooling their home.", term: "consumption" },
                    { definition: "Farmers use ___ to stop bugs and weeds from killing their crops.", term: "pesticides" },
                    { definition: "___ food is produced entirely without chemicals.", term: "organic" },
                    { definition: "Pollution is the ___ of many environmental problems.", term: "source" },
                    { definition: "When the cost of electricity increases, people are more likely to ___ energy.", term: "conserve" },
                ],
            },
        },
        {
            id: 3,
            name: "Unit 7: There's No Place Like Home",
            categories: {
                "Vocabulary Building": [
                    { term: "asset", definition: "a useful or valuable thing, person, or quality" },
                    { term: "hub", definition: "the center of a region" },
                    { term: "nurture", definition: "to care for, help, or encourage the development and growth" },
                    { term: "cultivate", definition: "to improve or develop by study or training" },
                    { term: "potential", definition: "capacity for growth and development; possibility" },
                ],
                "Real Talk": [
                    { term: "Cool!", definition: "Great!" },
                    { term: "Hold on!", definition: "Hold on!" },
                    { term: "out of touch", definition: "don’t have a realistic idea" },
                    { term: "reality check", definition: "an assessment of how realistic something is" },
                    { term: "an arm and a leg", definition: "a large amount of money" },
                    { term: "megabucks", definition: "a large amount of money" },
                    { term: "grand", definition: "thousand" },
                ],
                "Fill in the Blank": [
                    { definition: "The people showed ___ to the king by putting his face on the new coin.", term: "loyalty" },
                    { definition: "When children have nightmares, mothers give ___ with loving words.", term: "comfort" },
                    { definition: "The museum has a quiet and peaceful ___", term: "atmosphere" },
                    { definition: "Some houses are built from bricks and ___", term: "mortar" },
                    { definition: "They had no money to buy ___, so they used boxes as chairs.", term: "furniture" },
                    { definition: "We've had this couch too long. It's starting to look ___", term: "worn" },
                    { definition: "We used the tree for ___ during the storm.", term: "shelter" },
                    { definition: "A hotel with many rooms can ___ many people.", term: "lodge" },
                ],
            },
        },
        {
            id: 4,
            name: "Unit 8: The Sporting Life",
            categories: {
                "Vocabulary Building": [
                    { term: "milestone", definition: "a very important event in the development of another event or course of events" },
                    { term: "cross-country skiing", definition: "skiing across fields not down slopes" },
                    { term: "ski-jumping", definition: "a skiing event that involves jumping on a long steep sloping platform through the air as far as possible" },
                    { term: "merit", definition: "an advantage or positive feature" },
                    { term: "terrain", definition: "a particular type of land" },
                    { term: "be interspersed with", definition: "be combined with / interrupted by something at regular intervals" },
                    { term: "Alpine skiing", definition: "skiing downhill on skis with fixed heel binding" },
                    { term: "freestyle skiing", definition: "an acrobatic form of technical and aerial skiing" },
                    { term: "astounding", definition: "astonishing, amazing" },
                    { term: "spectator (sport)", definition: "a sport that people go to watch" },
                ],
                "Real Talk": [
                    { term: "up for", definition: "ready for" },
                    { term: "mess up", definition: "make a mistake" },
                    { term: "down pat", definition: "at the point of perfection" },
                    { term: "You bet!", definition: "Of course!" },
                    { term: "guts", definition: "courage" },
                    { term: "psyched", definition: "excited and psychologically prepared" },
                ],
                "Fill in the Blank": [
                    { definition: "The parade will begin with a ___ of students marching down the avenue.", term: "procession" },
                    { definition: "The board game chess ___ in India in the 6th century.", term: "originated" },
                    { definition: "The Eiffel Tower was built to ___ the 100th anniversary of the French Revolution.", term: "commemorate" },
                    { definition: "Thousands of runners participate in the ___ every year.", term: "marathon" },
                    { definition: "The new museum has ___ tourism in our city.", term: "revived" },
                    { definition: "The ___ of exchanging rings during a wedding ceremony dates back to ancient times.", term: "practice" },
                ],
            },
        },
    ],
};
